"""empty message

Revision ID: bf3628f7d034
Revises: 
Create Date: 2022-04-01 16:41:14.142070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf3628f7d034'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('amfn')
    op.drop_table('employee2')
    op.drop_table('client')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='post_pkey')
    )
    op.create_table('client',
    sa.Column('resnum', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('addr1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('addr2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marketvalue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('loanamtcurrent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('loanamtnew', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interestrate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('resnum', name='client_pkey')
    )
    op.create_table('employee2',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='employee2_pkey')
    )
    op.create_table('amfn',
    sa.Column('resnum', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('addr1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('addr2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip4', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marketvalue', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('loanamtcurrent', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('loanamtnew', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('payment', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interestrate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('apr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('resnum', name='amfn_pkey')
    )
    # ### end Alembic commands ###
